"use strict";
var __cov_aYFLdB2tsknlsNSv7ink8A = (Function('return this'))();
if (!__cov_aYFLdB2tsknlsNSv7ink8A.__coverage__) { __cov_aYFLdB2tsknlsNSv7ink8A.__coverage__ = {}; }
__cov_aYFLdB2tsknlsNSv7ink8A = __cov_aYFLdB2tsknlsNSv7ink8A.__coverage__;
if (!(__cov_aYFLdB2tsknlsNSv7ink8A['/Users/screen/codecoverage/UserController.js'])) {
   __cov_aYFLdB2tsknlsNSv7ink8A['/Users/screen/codecoverage/UserController.js'] = {"path":"/Users/screen/codecoverage/UserController.js","s":{"1":1,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"b":{"1":[0,0]},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"UserController","line":4,"loc":{"start":{"line":4,"column":0},"end":{"line":4,"column":37}}},"2":{"name":"(anonymous_2)","line":8,"loc":{"start":{"line":8,"column":43},"end":{"line":8,"column":54}}},"3":{"name":"(anonymous_3)","line":36,"loc":{"start":{"line":36,"column":32},"end":{"line":36,"column":52}}}},"statementMap":{"1":{"start":{"line":4,"column":0},"end":{"line":6,"column":1}},"2":{"start":{"line":5,"column":2},"end":{"line":5,"column":33}},"3":{"start":{"line":8,"column":0},"end":{"line":15,"column":2}},"4":{"start":{"line":9,"column":2},"end":{"line":14,"column":3}},"5":{"start":{"line":10,"column":4},"end":{"line":10,"column":46}},"6":{"start":{"line":12,"column":4},"end":{"line":12,"column":37}},"7":{"start":{"line":13,"column":4},"end":{"line":13,"column":46}},"8":{"start":{"line":36,"column":0},"end":{"line":38,"column":2}},"9":{"start":{"line":37,"column":2},"end":{"line":37,"column":42}}},"branchMap":{"1":{"line":9,"type":"if","locations":[{"start":{"line":9,"column":2},"end":{"line":9,"column":2}},{"start":{"line":9,"column":2},"end":{"line":9,"column":2}}]}}};
}
__cov_aYFLdB2tsknlsNSv7ink8A = __cov_aYFLdB2tsknlsNSv7ink8A['/Users/screen/codecoverage/UserController.js'];
function UserController(userStorage){__cov_aYFLdB2tsknlsNSv7ink8A.f['1']++;__cov_aYFLdB2tsknlsNSv7ink8A.s['2']++;this.userStorage=userStorage;}__cov_aYFLdB2tsknlsNSv7ink8A.s['3']++;UserController.prototype.getUserTemplate=function(){__cov_aYFLdB2tsknlsNSv7ink8A.f['2']++;__cov_aYFLdB2tsknlsNSv7ink8A.s['4']++;if(this.userTemplate){__cov_aYFLdB2tsknlsNSv7ink8A.b['1'][0]++;__cov_aYFLdB2tsknlsNSv7ink8A.s['5']++;return Promise.resolve(this.userTemplate);}else{__cov_aYFLdB2tsknlsNSv7ink8A.b['1'][1]++;__cov_aYFLdB2tsknlsNSv7ink8A.s['6']++;this.userTemplate=UserTemplate;__cov_aYFLdB2tsknlsNSv7ink8A.s['7']++;return Promise.resolve(this.userTemplate);}};__cov_aYFLdB2tsknlsNSv7ink8A.s['8']++;UserController.prototype.save=function(userModel){__cov_aYFLdB2tsknlsNSv7ink8A.f['3']++;__cov_aYFLdB2tsknlsNSv7ink8A.s['9']++;return this.userStorage.save(userModel);};
